version: '3'
services:
  nextjs:
    container_name: next-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    # ports:
    #   - 3000:3000
    networks:
      - win_network
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - win_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  win_network:
    external: true